Todolist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from register import views as v #differentiate from other views


urlpatterns = [
    path('admin/', admin.site.urls), #admin dashboard
    path('', include("list.urls")), #main url. Automatically directed to the list.urls file. Link this to urls.py in "list" application
    path('<int:id>',include("list.urls")),
    path('todolist/',include("list.urls")),
    path('timeboxing/',include("list.urls")),
    path('register/', v.register, name="register"), # create a simple urls without urls from the application
    path('profile/', v.profile, name="profile"),
    path('', include("django.contrib.auth.urls")), # django will get to django.contrib.auth application and go to urls file
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #add the path. static files. 2 arguments. 1 for the url and 1 from the root. 

#  path('<str:name>', include("list.urls")),

list/urls.py
from django.urls import path
from . import views
from . import list
from . import timebox
from django.conf import settings
from django.conf.urls.static import static

# Define the path to different webpages. Represent the urls to different pages

urlpatterns = [
    path("", views.home, name="home"), #if we go to a homepage, where the path is default,
                                       # we're gonna view the view.index page that has a name of "index". view.index. index = function name
    path("<int:id>",views.todo, name="todo"), #the path is int we called it an id. That id is dynamic.
    path("todolist/", list.list, name="todolist"),
    path("timeboxing/", timebox.timebox, name="timeboxing"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# path("<str:name>", views.idk, name="idk"),

list/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tools(models.Model):
    name = models.CharField(max_length=200)
    img = models.ImageField(null=True, blank=True, upload_to="images/")

    def __str__(self):
        return self.name

class ToDoList(models.Model): #this class is inherited from models.Model. We're creating a database object
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True) # foreign key of class User in django.contrib.auth.models. access it through
    name = models.CharField(max_length=200) # name is the name of the attribute. Models.... is the name of the field that we want to store in database

    def __str__(self):
        return self.name #if we want to print, it will come out

class ToDoList_w(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True) # foreign key of class User in django.contrib.auth.models. access it through
    name = models.CharField(max_length=200)
    weekNum = models.CharField(max_length=200, default=0)

    def __str__(self):
        return self.name

class Item(models.Model):
    todolist = models.ForeignKey(ToDoList, on_delete=models.CASCADE) # define that we use a foreign key, which is ToDoList object when we create an item
                                                                     # if we delete ToDoList, we delete Item aswell. ToDoList is associated with many todolist object
    text = models.CharField(max_length=300) # Basically it's a string of data. #You need a max length
    complete = models.BooleanField()

    def __str__(self):
        return self.text
    
class Item_w(models.Model):
    todolist = models.ForeignKey(ToDoList_w, on_delete=models.CASCADE) # define that we use a foreign key, which is ToDoList object when we create an item
                                                                     # if we delete ToDoList, we delete Item aswell. ToDoList is associated with many todolist object
    text = models.CharField(max_length=300) # Basically it's a string of data. #You need a max length
    complete = models.BooleanField()
    
    def __str__(self):
        return self.text
    
class ListOfWeekNum(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    weekId = models.IntegerField()

    def __str__(self):
        return self.weekId
    
class TemplateList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True) # foreign key of class User in django.contrib.auth.models. access it through
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class TemplateItem(models.Model):
    todolist = models.ForeignKey(TemplateList, on_delete=models.CASCADE) # define that we use a foreign key, which is ToDoList object when we create an item
                                                                     # if we delete ToDoList, we delete Item aswell. ToDoList is associated with many todolist object
    text = models.CharField(max_length=300) # Basically it's a string of data. #You need a max length
    complete = models.BooleanField()
    
    def __str__(self):
        return self.text
    
class Images(models.Model):
    name = models.CharField(max_length=300, default="img")
    image = models.ImageField(null=True, blank=True, upload_to="images/")

    def __str__(self):
        return self.name


'''
source = https://docs.djangoproject.com/en/4.2/topics/db/examples/many_to_one/

t = ToDoList(name="first list")
t.save()
t2 = ToDoList(name="second list")
i = Item(id=None, todolist=t, text="wake up", complete=False)
i.save()
j = Item.objects.all()
j.save()
# t.item_set.all() #<Item: wake up>
# i.todolist = first list
# i.todolist.id = 1
# t.item_set.count() = 1
# Item.objects.all() #<Item: wake up>

t = i.todolist

- create new item in first list via the ToDoList object
new_item = t.item_set.create(text="take a shower", complete=False) 
# new_item = <Item: take a shower>
# new_item.todolist.id = 1
# new_item.todolist = first list

- create new item casually. Another way
new_item2 = Item.objects.create(text="brush a teeth", complete=False, todolist=t) 

- move an item to a different todolist set/ToDoList.
t2.item_set.add(new_item2)
# new_item2.todolist = <Item: second list>

- filtering
Item.objects.filter(todolist__name="first list") # item in first list
t.item_set.filter(text__startswith="wake") # item in first list that starts with "wake"

- Deleting #if ToDoList is deleted, the Item inside of that ToDolist is also deleted
t.delete()
del_object = t.get(id=1)
del_object.delete() #delete ToDoList


'''

list/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import ToDoList, Item, ToDoList_w, Item_w, ListOfWeekNum, TemplateList, TemplateItem, Images, Tools
from .timebox_models import Timebox, ItemSchedule, ItemGoal, ItemPriority, ListOfWeekNum_2
from .form import CreateNewList, ChangeListName, CreateNewItem
from django.contrib.auth import get_user_model # get the user list
import time
import math
from .dayFuture import dayFuture



def index(response):
    ls = ToDoList.objects.get(id=1)  # get the object in database

    # if response.method == "POST": # the dict: {"save":["save"], "c1":[""],}
    #     pass

    return render(response,"main/base2.html", {"ls":ls})

def home(response):
    tools = Tools.objects.all()
    return render(response, "main/home.html", {"tools":tools,})

def todo(response,id): # parameter id is from the url.
    ls = ToDoList.objects.get(id=id)  # get the object in database
    item = ls.item_set.get(id=1)

    return HttpResponse("<h1>%s</h1><br></br><p>%s</p>" %(ls.name, str(item.text))) #display the name of ToDoList object that has the id according to the url page.
    # If we go to urlpage 1/, we'll get Tim's List and item of Tim's List with the id of 1.
    # return HttpResponse("<h1>%s<h1>" % id) # display the number in the webpage according to the id. #First step to display dinamic pages

list/templates/main/base2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <!--bootstrap-->
    <link href"{% static 'css\main.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %} TimeMaster {% endblock %}</title> <!-- This way, we can change the title based on the pages. WebGame is default title-->

    {% block head %}
    {% endblock head %}

    <style>
      * {
        font-family: sans-serif;
        text-decoration: None;
      }
      .nav-link {
        color:#edf0f1;
      }
      .nav-link:hover {
        {% comment %} transform: translate(10px,10px); {% endcomment %}
        color:#edf0f1;
      }

    </style>

</head>
<body>

<div class="navigation">
    <nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color:#24252A; height:75px; ">
        <div class="container-fluid" style="">

          <a class="navbar-brand" href="#" style="color:#edf0f1;">TimeMaster</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarText" style="margin-left:50px; display:grid; grid-template-columns: auto auto auto auto auto; grid-column-gap:50px">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="../">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Help</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Feedback</a>
            </li>
          </ul>
            </div>

            <span class="navbar-text" style="color:white">
              {% if user.is_authenticated %}
              <span class="navbar-text"><a class="nav-link" href="/profile" style="background-color:brightblue; border-radius:15px; padding:10px;">{{user}}</a></span>
            {% else %}
            <span class="navbar-text"><a class="nav-link" href="/login" style="border-radius:15px; padding:10px;";>Log in</a></span>
            <span class="navbar-text">|</span>
            <span class="navbar-text"><a class="nav-link" href="/register" style="border-radius:15px; padding:10px; ";>Sign up</a></span>
            {% endif %}
            </span>

          </div>
        </div>
      </nav>


</div>

<div id="content" ,name="content", class="main">
    {% block content %} <!--So, all of the block content in other templates will go to base2.html content-->

    {% endblock %}
</div>  <!-- name is a variable in view.py, But, views.py must return that variable first -->

<!--Bootstrap installation-->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<!--ionicons installation-->
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>



{% block scripts %}

{% endblock scripts %}

</body>
</html>

list/templates/main/dashboard.html
<!DOCTYPE html>
<html lang="en">
    {% extends "main/base2.html" %}
    {% load static %}
<head>
    

    <title>{% block title %} Dashboard {% endblock %}</title>
</head>
<body>
    {% block content %}
    woe
    <button id="clickBtn">yes</button>
    {% endblock content %}

    {% block scripts %}
        <script src="{% static 'dashboard.js' %}"></script>
    {% endblock scripts %}

</body>
</html>

list/templates/main/home.html
<!DOCTYPE html>
{% extends "main/base2.html" %}
<html lang="en">
<head>

    <!--bootstrap-->
    {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> {% endcomment %}
    
    <meta charset="UTF-8">
    <title>{% block title %}TimeMaster{% endblock %}</title>
  

</head>

<body>

  

<div id="content" ,name="content", class="main">
    {% block content %} <!--inside this block content, the elements will be pasted to the parent elements which is base2.html-->
    
    <!--Side Nav User-->
    <ul class="nav flex-column" style="background-color:blue">
      {% for i in users %}
      <li class="nav-item" >
        <a class="nav-link" href="#">{{i}}</a>
      </li>
      {% endfor %}
    </ul>

    <!--Main Game Display-->
  <div class="container-fluid" style="margin:50px; max-width:95%;">
    <h1 style="margin-right:auto; margin-left:auto; text-align:center;">Pick Your Productivity Tools!</h1>
    <div class="container my-5" style="display:flex; flex-direction:row;">
    <div class="row">
        {% for tool in tools %}
        <div class="col-auto">
        <div class="card" style=
        "width: 275px;
        margin:50px;
      
        ">
        <a href="{{tool.name}}">
            <img src={{tool.img.url}} class="card-img-top" alt={{tool.name}} style="height:250px;">
            <div class="card-body">
              <p class="card-text" style="color:black; text-align:center">{{tool.name}}</p>
            </div>
          </a>
          </div>
        </div> <!--col-->
          {% endfor %}
        </div> <!--row-->
    </div> <!--container my-5-->
  </div> <!--container-->

    <!--Modal Feedback-->
    <div class="modal-dialog modal-dialog-centered">
      ...
    </div>

    <!-- Button trigger modal -->
    <form>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <p>huh</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
</form>

    {% endblock %}
</div>

<!--Bootstrap installation-->
{% comment %} <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> {% endcomment %}

</body>
</html>


list/templates/main/list.html
<!DOCTYPE html>
{% extends "main/base2.html" %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} View List {% endblock %}</title>
    
    {% block head %}
    <link rel="stylesheet" type="text/css" href="{% static '/css/list.css' %}">
    {% endblock head %}

</head>
<body>
{% block content %}
    <!--Display Weekly Todolist  ==-->
    <div class="container c1">

        <div class="d-flex justify-content-center">
            <form method="post" action="/todolist/">
                {% csrf_token %}
                {% if weekly_todolist == False %}
                    {% if user.is_authenticated %}
                        <button type="submit" value="muah" name="create_template_ls" style="background-color:transparent; border:none; ">
                            <div style=""><img src={{img_plus.image.url}} style="width=80px; height:80px"></div>
                            <p>Create New Weekly Todolist</p>
                        </button>
                    {% else %}
                        <button type="button" style="padding:50px; background-color:transparent; border:none; " data-container="body" data-toggle="popover" data-placement="right" data-content="Please login to save list">
                            <div style=""><img src={{img_plus.image.url}} style="width=80px; height:80px"></div>
                            <p>Create New Weekly Todolist</p>
                        </button>
                    {% endif %}
                {% else %}
                <div style="padding:20px">
                <button type="submit" class="btn btn-primary btn_1" value="muah" name="create_template_ls" style="">
                    Create Todolist for another week
                </button>
                <button type="submit" class="btn btn-primary" value="muah" name="delete_all_list_week">Delete all List</button>
                <div class="d-flex justify-content-center line"></div>
            </div>
                {% endif %}
                
            </form>
        </div>
        
        <div class="row all_todolist" style="">
            {% for list in lw %}
                {% if list.user == user %} <!--Display only the current user's list-->
                
                    {% if forloop.counter|divisibleby:8 or forloop.counter == 1 %}
                        {% comment %} <div style=""> 
                            <form method="post" action="/list/">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary" name="templateWeek" value="{{list.weekNum}}">Set as template</button> <!--all the information in this form will be passed to the view.py by dictionary--><!--the submit button in form in django is automatically set-->
                                <button type="submit" class="btn btn-primary" name="" value="">Delete This Week's List</button>
                            </form>
                        </div> {% endcomment %}
                    {% endif %}
                    
                    <div class="col-auto todolist_outer" > <!--Whole Todolist-->
                        <div class="todolist_inner">
                            <div class="list_head" style="display:flex; flex-direction:row; justify-content:space-around;">
                                <div>{{list.name}} </div>
                            </div>
                            
                        <!--List of the Item in all Todolist-->
                            <form method="post" action="/todolist/">
                                {% csrf_token %}
                                <ul class="list_items">
                                    {% for i in list.item_w_set.all %} <!-- Looping all the items in ls.item_set.all(). When you are looping something, leave the brackets in ls.item_set.all() -->
                                        {% if i.complete == False %} <!--if it isn't completed, show it in the list-->
                                            <li class="list_item">
                                                <input type="checkbox" name="{{list.id}}c{{i.id}}" value="clicked_week"> <!--check whether it's complete or not-->
                                                {{i.text}}
                                                <button type="submit" class="btn deleteList" name="deleteItem_week" value="delete{{list.id}}c{{i.id}}"><ion-icon name="close-outline" class="closeButton" style="margin-left:10px;"></ion-icon></button> <!--delete particular item-->
                                            </li>
                                        {% else %}
                                            <li class="list_item">
                                                <input type="checkbox" name="{{list.id}}c{{i.id}}" value="clicked_week" checked> <!--the default is checked-->
                                                {{i.text}}
                                                <button type="submit" class="btn deleteList" name="deleteItem_week" value="delete{{list.id}}c{{i.id}}" style="margin-left:10px;"><ion-icon name="close-outline" class="closeButton" style=""></ion-icon></button> <!--delete particular item-->
                                            </li>
                                        {% endif %}
                                    {% endfor %} <!--end the for loop-->
                                </ul>
                                <button type="submit" name="save_week" value="{{list.id}}" class="btn btn-primary">Save Changes</button> <!--the default is checked--> <!--when the button is saved, it will send the
                                value, which is "save" as a dictionary to views.py. {"save":["save"]}
                                                                                {"name":["value"]}-->   
                            </form>
                            
                
                            <!--Create new Item-->
                            <form method="post" action="/todolist/">
                                {% csrf_token %}
                                {{form_w.as_p}} 
                                <button type="submit" name="newItem_week" value="submit{{list.id}}">Create New</button> <!--all the information in this form will be passed to the view.py by dictionary--><!--the submit button in form in django is automatically set-->
                            </form>

                        </div> <!--Todolist_inner-->

                        <div class="deleteList_1">
                            <form method="post" action="/todolist/">
                                {%csrf_token%}
                                <button type="submit" class="btn deleteList" value="{{list.id}}" name="delete_ls_week"><ion-icon name="close-outline" class="closeButton" style=""></ion-icon></button>
                            </form>
                        </div>

                    </div> <!--Whole ToDoList-->
                
                    {% if forloop.counter|divisibleby:7 %}
                        <div class="d-flex justify-content-center line"></div>
                    {% endif %}

                {% endif %}
            {% endfor %}
        </div> <!--row row-cols-2-->
        

    </div>



    <!--Display Original ToDoList-->
    <div class="container c1">
        <div class="d-flex justify-content-center flexContainer">
            <button  id="listButton" type="button" value="muah" name="create_ls_1" style="background-color:transparent; border:none">
                <div style=""><img src={{img_plus.image.url}} style="width=80px; height:80px"></div>
                <p>Create New Additional Todolist</p>
            </button>
        </div>

        <div class="row">
        {% for list in ls %}
        {% if list.user == user %} <!--Display only the current user's list-->
        <div class="col" >
        <h1>{{list.name}}</h1>


        <!--Change Todolist Name-->
        <form method="post" action="/todolist/"> 
            {% csrf_token %}
            {{form2.as_p}}
            <button type="submit" class="btn btn-primary" value="{{list.id}}" name="change_ls">Change List Name</button> <!--the button is automatically set for submitting the form-->
        </form>

        <!--List of the Item in all Todolist-->
        <form method="post" action="/todolist/">
            {% csrf_token %}
            <button type="submit" class="btn btn-secondary" value="{{list.id}}" name="delete_ls">Delete List</button>
        <ul>
        {% for i in list.item_set.all %} <!-- Looping all the items in ls.item_set.all(). When you are looping something, leave the brackets in ls.item_set.all() -->
            {% if i.complete == False %} <!--if it isn't completed, show it in the list-->
            <li>
                <input type="checkbox" name="{{list.id}}c{{i.id}}" value="clicked" > <!--check whether it's complete or not-->
                {{i.text}}
            </li>
            {% else %}
            <li>
                <input type="checkbox" name="{{list.id}}c{{i.id}}" value="clicked" checked> <!--the default is checked-->
                {{i.text}}
            </li>
            {% endif %}
            
            <button type="submit" name="deleteItem" value="delete{{list.id}}c{{i.id}}">Delete Item</button> <!--delete particular item-->
        {% endfor %} <!--end the for loop-->
        </ul>
        <button type="submit" name="save" value="{{list.id}}">Save</button> <!--the default is checked--> <!--when the button is saved, it will send the
            value, which is "save" as a dictionary to views.py. {"save":["save"]}
                                                            {"name":["value"]}-->   
        </form>

        
        <!--Create new Item-->
        <form method="post" action="/todolist/">
            {% csrf_token %}<!--This element must go inside a form element. IDK the reason-->
            {{form.as_p}} <!--Pass a form object and django will automatically create a form for us-->
            <!--{{form.as_table}} is the default one. {{form.as_p}} is the vertical form. {{form.as_ul}} as a list-->
        <button type="submit" name="newItem" value="submit{{list.id}}">Create New</button> <!--all the information in this form will be passed to the view.py by dictionary--><!--the submit button in form in django is automatically set-->
        </form>
        
    </div> <!--col-->
        {% endif %}
    {% endfor %}
    </div> <!--row-->

    
    <!--Create New List-->
    <form method="post" action="/todolist/">
        {% csrf_token %}
        {{form3.as_p}}
        {% if user.is_authenticated %}
            <button type="submit" class="btn btn-primary" value="muah" name="create_ls">Create New List</button>
        {% else %}
            <button type="button" class="btn btn-primary" data-container="body" data-toggle="popover" data-placement="right" data-content="Please login to save list">Create New List</button>
        {% endif %} 
    </form>

    <form method="post" action='/todolist/'>
        {% csrf_token %}
        <button type="submit" class="btn btn-primary" value="muah" name="delete_all_list">Delete all List</button>
    </form>
    

</div> <!--container c1 (additional todolist)-->

{% endblock content %}

{% block scripts %}
<script>
    $( function( ) {
        $( "[data-toggle='popover'").popover();
    } )
</script>
{% endblock scripts %}

</body>
</html>



